-- Migration to expand treatments table schema
alter table public.treatments
  add column if not exists alternative_names text[] not null default '{}',
  add column if not exists conditions_treated text[] not null default '{}',
  add column if not exists anaesthesia_sedation text not null default '',
  add column if not exists expected_outcome text not null default '',
  add column if not exists expected_longevity text not null default '',
  add column if not exists unsuitable_candidates text not null default '',
  add column if not exists alternative_treatments text not null default '',
  add column if not exists before_preparation text not null default '',
  add column if not exists when_contact_clinic text not null default '',
  add column if not exists when_book_consultation text not null default '',
  add column if not exists faq_json jsonb not null default '[]'::jsonb,
  add column if not exists pricing_display_type text not null default 'consultation_required',
  add column if not exists min_price numeric(12,2) check (min_price is null or min_price >= 0),
  add column if not exists max_price numeric(12,2) check (max_price is null or max_price >= 0),
  add column if not exists currency text not null default 'INR',
  add column if not exists pricing_note text not null default '',
  add column if not exists price_verified_date date,
  add column if not exists additional_gallery text[] not null default '{}',
  add column if not exists before_after_gallery jsonb not null default '[]'::jsonb,
  add column if not exists before_after_consent boolean not null default false,
  add column if not exists written_by text not null default '',
  add column if not exists clinically_reviewed_by text not null default '',
  add column if not exists reviewer_credentials text not null default '',
  add column if not exists reviewer_profile_id uuid references public.doctors(id) on delete set null,
  add column if not exists last_reviewed_at date,
  add column if not exists clinical_references text[] not null default '{}',
  add column if not exists canonical_url_override text,
  add column if not exists allow_search_indexing boolean not null default true,
  add column if not exists social_title text not null default '',
  add column if not exists social_description text not null default '',
  add column if not exists social_image text not null default '',
  add column if not exists primary_search_phrase text not null default '',
  add column if not exists secondary_search_phrases text[] not null default '{}',
  add column if not exists structured_data_type text not null default 'MedicalProcedure',
  add column if not exists structured_data_status text not null default 'Pending',
  add column if not exists sitemap_status text not null default 'Included';
